"""
Données de planification AT de base par jour-type et saison
"""
import numpy as np

DATA = {
    "Lundi Standard": {
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*24 + [np.nan]*6,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*29 + [np.nan]*10,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*32 + [np.nan]*6,
        "Check in 1": [np.nan]*1 + [1]*28 + [np.nan]*10,
        "Check in 2": [np.nan]*9 + [1]*20 + [np.nan]*10,
        "Guichet info": [np.nan]*9 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*9 + [1]*28 + [np.nan]*2,
        "Priority Lane": [np.nan]*1 + [1]*28 + [np.nan]*10,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Lundi Été": {
        "Accueil famille AE": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Accueil famille CSC": [1]*28 + [np.nan]*12,
        "Aile Est Arrivée": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée dispatch": [np.nan]*4 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [np.nan]*2 + [1]*34 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*2 + [1]*34 + [np.nan]*4,
        "Check in 1": [1]*30 + [np.nan]*10,
        "Check in 2": [np.nan]*2 + [1]*30 + [np.nan]*8,
        "Guichet info": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Hall bagage (+ Transfert)": [np.nan]*14 + [1]*24 + [np.nan]*2,
        "Priority Lane": [1]*32 + [np.nan]*8,
        "Sect. France": [np.nan]*28 + [1]*4 + [np.nan]*8,
        "Transit": [np.nan]*2 + [1]*34 + [np.nan]*4,
        "Visitor's Center": [np.nan]*6 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Lundi Hiver": {
        "Accueil famille CSC": [1]*31 + [np.nan]*8,
        "Accès Sect. France": [np.nan]*9 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*29 + [np.nan]*1,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*34 + [np.nan]*4,
        "Check in 1": [np.nan]*1 + [1]*26 + [np.nan]*12,
        "Check in 2": [np.nan]*5 + [1]*28 + [np.nan]*6,
        "Guichet info": [np.nan]*9 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*9 + [1]*29 + [np.nan]*1,
        "Priority Lane": [1]*29 + [np.nan]*10,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Mardi Standard": {
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*22 + [np.nan]*8,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*32 + [np.nan]*6,
        "Check in 1": [np.nan]*1 + [1]*24 + [np.nan]*14,
        "Guichet info": [np.nan]*9 + [1]*16 + [np.nan]*14,
        "Hall bagage (+ Transfert)": [np.nan]*13 + [1]*24 + [np.nan]*2,
        "Priority Lane": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Mardi Été": {
        "Accueil famille CSC": [1]*28 + [np.nan]*12,
        "Aile Est Arrivée": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée dispatch": [np.nan]*4 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [np.nan]*2 + [1]*34 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*2 + [1]*34 + [np.nan]*4,
        "Check in 1": [1]*30 + [np.nan]*10,
        "Guichet info": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Hall bagage (+ Transfert)": [np.nan]*10 + [1]*28 + [np.nan]*2,
        "Priority Lane": [1]*32 + [np.nan]*8,
        "Transit": [np.nan]*2 + [1]*32 + [np.nan]*6,
        "Visitor's Center": [np.nan]*6 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Mardi Hiver": {
        "Accès Sect. France": [np.nan]*9 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*29 + [np.nan]*1,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*34 + [np.nan]*4,
        "Check in 1": [np.nan]*1 + [1]*26 + [np.nan]*12,
        "Check in 2": [np.nan]*5 + [1]*28 + [np.nan]*6,
        "Guichet info": [np.nan]*9 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*9 + [1]*29 + [np.nan]*1,
        "Priority Lane": [1]*29 + [np.nan]*10,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Mercredi Standard": {
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*22 + [np.nan]*8,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*32 + [np.nan]*6,
        "Check in 1": [np.nan]*1 + [1]*24 + [np.nan]*14,
        "Guichet info": [np.nan]*9 + [1]*16 + [np.nan]*14,
        "Hall bagage (+ Transfert)": [np.nan]*13 + [1]*24 + [np.nan]*2,
        "Priority Lane": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Mercredi Été": {
        "Accueil famille CSC": [1]*28 + [np.nan]*12,
        "Aile Est Arrivée": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée dispatch": [np.nan]*4 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [np.nan]*2 + [1]*34 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*2 + [1]*34 + [np.nan]*4,
        "Check in 1": [1]*30 + [np.nan]*10,
        "Guichet info": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Hall bagage (+ Transfert)": [np.nan]*10 + [1]*28 + [np.nan]*2,
        "Priority Lane": [1]*32 + [np.nan]*8,
        "Transit": [np.nan]*2 + [1]*32 + [np.nan]*6,
        "Visitor's Center": [np.nan]*6 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Mercredi Hiver": {
        "Accès Sect. France": [np.nan]*9 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*29 + [np.nan]*1,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*34 + [np.nan]*4,
        "Check in 1": [np.nan]*1 + [1]*26 + [np.nan]*12,
        "Check in 2": [np.nan]*5 + [1]*28 + [np.nan]*6,
        "Guichet info": [np.nan]*9 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*9 + [1]*29 + [np.nan]*1,
        "Priority Lane": [1]*29 + [np.nan]*10,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Jeudi Standard": {
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*22 + [np.nan]*8,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*32 + [np.nan]*6,
        "Check in 1": [np.nan]*1 + [1]*24 + [np.nan]*14,
        "Guichet info": [np.nan]*9 + [1]*16 + [np.nan]*14,
        "Hall bagage (+ Transfert)": [np.nan]*13 + [1]*24 + [np.nan]*2,
        "Priority Lane": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Jeudi Été": {
        "Accueil famille CSC": [1]*28 + [np.nan]*12,
        "Aile Est Arrivée": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée dispatch": [np.nan]*4 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [np.nan]*2 + [1]*34 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*2 + [1]*34 + [np.nan]*4,
        "Check in 1": [1]*30 + [np.nan]*10,
        "Guichet info": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Hall bagage (+ Transfert)": [np.nan]*10 + [1]*28 + [np.nan]*2,
        "Priority Lane": [1]*32 + [np.nan]*8,
        "Transit": [np.nan]*2 + [1]*32 + [np.nan]*6,
        "Visitor's Center": [np.nan]*6 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Jeudi Hiver": {
        "Accès Sect. France": [np.nan]*9 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*29 + [np.nan]*1,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*34 + [np.nan]*4,
        "Check in 1": [np.nan]*1 + [1]*26 + [np.nan]*12,
        "Check in 2": [np.nan]*5 + [1]*28 + [np.nan]*6,
        "Guichet info": [np.nan]*9 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*9 + [1]*29 + [np.nan]*1,
        "Priority Lane": [1]*29 + [np.nan]*10,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Vendredi Standard": {
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*24 + [np.nan]*6,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*29 + [np.nan]*10,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*32 + [np.nan]*6,
        "Check in 1": [np.nan]*1 + [1]*28 + [np.nan]*10,
        "Guichet info": [np.nan]*9 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*9 + [1]*28 + [np.nan]*2,
        "Priority Lane": [np.nan]*1 + [1]*28 + [np.nan]*10,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Vendredi Été": {
        "Accueil famille AE": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Accueil famille CSC": [1]*28 + [np.nan]*12,
        "Aile Est Arrivée": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée dispatch": [np.nan]*4 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [np.nan]*1 + [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*35 + [np.nan]*4,
        "Check in 1": [1]*28 + [np.nan]*12,
        "Check in 2": [1]*32 + [np.nan]*8,
        "Guichet info": [np.nan]*10 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*14 + [1]*24 + [np.nan]*2,
        "Priority Lane": [np.nan]*10 + [1]*22 + [np.nan]*8,
        "Transit": [np.nan]*1 + [1]*35 + [np.nan]*4,
        "Visitor's Center": [np.nan]*6 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Vendredi Hiver": {
        "Accueil famille CSC": [1]*31 + [np.nan]*8,
        "Accès Sect. France": [np.nan]*9 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*29 + [np.nan]*1,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*34 + [np.nan]*4,
        "Check in 1": [np.nan]*1 + [1]*26 + [np.nan]*12,
        "Check in 2": [np.nan]*5 + [1]*28 + [np.nan]*6,
        "Guichet info": [np.nan]*9 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*9 + [1]*29 + [np.nan]*1,
        "Priority Lane": [1]*29 + [np.nan]*10,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Samedi Standard": {
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*24 + [np.nan]*6,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*29 + [np.nan]*10,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*32 + [np.nan]*6,
        "Check in 1": [np.nan]*1 + [1]*28 + [np.nan]*10,
        "Guichet info": [np.nan]*9 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*9 + [1]*28 + [np.nan]*2,
        "Priority Lane": [np.nan]*1 + [1]*28 + [np.nan]*10,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Samedi Été": {
        "Accueil famille AE": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Accueil famille CSC": [1]*28 + [np.nan]*12,
        "Aile Est Arrivée": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée dispatch": [np.nan]*4 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [np.nan]*1 + [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*35 + [np.nan]*4,
        "Check in 1": [1]*28 + [np.nan]*12,
        "Check in 2": [np.nan]*4 + [1]*28 + [np.nan]*8,
        "Guichet info": [np.nan]*10 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*14 + [1]*24 + [np.nan]*2,
        "Priority Lane": [1]*28 + [np.nan]*12,
        "Transit": [np.nan]*1 + [1]*35 + [np.nan]*4,
        "Visitor's Center": [np.nan]*6 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Samedi Hiver": {
        "Accueil famille CSC": [1]*31 + [np.nan]*8,
        "Accès Sect. France": [np.nan]*7 + [1]*22 + [np.nan]*10,
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*7 + [1]*31 + [np.nan]*1,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [np.nan]*1 + [1]*32 + [np.nan]*6,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*34 + [np.nan]*4,
        "Check in 1": [np.nan]*1 + [1]*32 + [np.nan]*6,
        "Check in 2": [np.nan]*1 + [1]*32 + [np.nan]*6,
        "Check in 3": [1]*29 + [np.nan]*10,
        "Guichet info": [np.nan]*5 + [1]*24 + [np.nan]*10,
        "Hall bagage (+ Transfert)": [np.nan]*9 + [1]*22 + [np.nan]*4 + [1]*3 + [np.nan]*1,
        "Priority Lane": [1]*29 + [np.nan]*10,
        "T2 Arrivée": [np.nan]*7 + [1]*22 + [np.nan]*10,
        "T2 Départ": [np.nan]*5 + [1]*24 + [np.nan]*10,
        "T2 Portier": [np.nan]*5 + [1]*24 + [np.nan]*10,
        "T2 Renfort": [np.nan]*7 + [1]*12 + [np.nan]*20,
        "Transit": [np.nan]*5 + [1]*24 + [np.nan]*10,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Dimanche Standard": {
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*9 + [1]*24 + [np.nan]*6,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [1]*29 + [np.nan]*10,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*32 + [np.nan]*6,
        "Check in 1": [np.nan]*1 + [1]*28 + [np.nan]*10,
        "Guichet info": [np.nan]*9 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*9 + [1]*28 + [np.nan]*2,
        "Priority Lane": [np.nan]*1 + [1]*28 + [np.nan]*10,
        "Transit": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Dimanche Été": {
        "Accueil famille AE": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Accueil famille CSC": [1]*28 + [np.nan]*12,
        "Aile Est Arrivée": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*6 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*10 + [1]*20 + [np.nan]*10,
        "Aile Est Arrivée dispatch": [np.nan]*4 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [np.nan]*1 + [1]*35 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*35 + [np.nan]*4,
        "Check in 1": [1]*28 + [np.nan]*12,
        "Check in 2": [np.nan]*4 + [1]*24 + [np.nan]*12,
        "Guichet info": [np.nan]*10 + [1]*18 + [np.nan]*12,
        "Hall bagage (+ Transfert)": [np.nan]*10 + [1]*28 + [np.nan]*2,
        "Priority Lane": [1]*32 + [np.nan]*8,
        "Transit": [np.nan]*1 + [1]*35 + [np.nan]*4,
        "Visitor's Center": [np.nan]*6 + [1]*4 + [np.nan]*20 + [1]*10,
    },
    "Dimanche Hiver": {
        "Accueil famille CSC": [1]*31 + [np.nan]*8,
        "Accès Sect. France": [np.nan]*7 + [1]*22 + [np.nan]*10,
        "Aile Est Arrivée": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée ABC": [np.nan]*5 + [1]*34,
        "Aile Est Arrivée Transf.": [np.nan]*7 + [1]*31 + [np.nan]*1,
        "Aile Est Arrivée dispatch": [np.nan]*3 + [1]*26 + [np.nan]*10,
        "Aile Est Départ": [np.nan]*1 + [1]*34 + [np.nan]*4,
        "Aile Est Départ ABC": [np.nan]*1 + [1]*34 + [np.nan]*4,
        "Check in 1": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Check in 2": [np.nan]*1 + [1]*30 + [np.nan]*8,
        "Check in 3": [1]*29 + [np.nan]*10,
        "Guichet info": [np.nan]*5 + [1]*24 + [np.nan]*10,
        "Hall bagage (+ Transfert)": [np.nan]*7 + [1]*31 + [np.nan]*1,
        "Priority Lane": [1]*29 + [np.nan]*10,
        "T2 Arrivée": [np.nan]*7 + [1]*22 + [np.nan]*10,
        "T2 Départ": [np.nan]*7 + [1]*22 + [np.nan]*10,
        "T2 Portier": [np.nan]*7 + [1]*22 + [np.nan]*10,
        "T2 Renfort": [np.nan]*7 + [1]*12 + [np.nan]*20,
        "Transit": [np.nan]*5 + [1]*24 + [np.nan]*10,
        "Visitor's Center": [np.nan]*5 + [1]*4 + [np.nan]*20 + [1]*10,
    },
}
